name: imageTest
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  MXNET170_v0-0-2:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/mxnet170:v0.0.2
    timeout-minutes: 60
    steps:
      - run: cat /etc/os-release
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
  MXNET170_v0-0-1:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/mxnet170:v0.0.1
    timeout-minutes: 60
    steps:
      - run: cat /etc/os-release
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
  TENSORFLOW:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/applications/mnistcalculator/tensorflow
    timeout-minutes: 60
    steps:
      - run: cat /etc/os-release
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
  MXNET190_v0-0-2:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/mxnet/190:v0.0.2
    timeout-minutes: 60
    steps:
      - run: cat /etc/os-release
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
  TENSORFLOWONNX:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/tensorflow-onnx:latest
    timeout-minutes: 60
    steps:
      - run: cat /etc/os-release
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
  integrationmxnet0-0-3:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/integrationtests/mxnet:v0.0.3
    timeout-minutes: 60
    steps:
      - run: cat /etc/os-release
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
  mxnwt170onnx:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/mxnet170-onnx:v0.0.1
    timeout-minutes: 60
    steps:
      - run: cat /etc/os-release
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
