name: imageTest
on:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  MXNET170_v0-0-2:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/mxnet170:v0.0.2
    timeout-minutes: 60
    steps:
      - run: cat /etc/os-release
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
  MXNET170_v0-0-1:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/mxnet170:v0.0.1
    timeout-minutes: 60
    steps:
      - run: cat /etc/os-release
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
  MXNET190_v0-0-2:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/mxnet/190:v0.0.2
    timeout-minutes: 60
    steps:
      - run: cat /etc/os-release
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
  TENSORFLOWONNX:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/tensorflow-onnx:latest
    timeout-minutes: 60
    steps:
      - run: cat /etc/os-release
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
  integrationmxnet0-0-3:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/integrationtests/mxnet:v0.0.3
    timeout-minutes: 60
    steps:
      - run: cat /etc/os-release
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
  mxnwt170onnx:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/mxnet170-onnx:v0.0.1
    timeout-minutes: 60
    steps:
      - run: cat /etc/os-release
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
  tensorflowMNIST:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/applications/mnistcalculator/tensorflow
    timeout-minutes: 60
    steps:
      - run: cat /etc/os-release
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
  CheckoutTest:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/applications/mnistcalculator/tensorflow
    timeout-minutes: 60
    steps:
      - run: cat /etc/os-release
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Clone repository
        env:
          REPO_URL: https://github.com/DavidBlm/MNISTPipeline
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          git clone https://$GITHUB_TOKEN@github.com/DavidBlm/MNISTPipeline repository
          cd repository
          git fetch origin +refs/heads/*:refs/remotes/origin/*
          git reset --hard origin/$(git rev-parse --abbrev-ref HEAD)
          ls
      #- name: Checkout
      #  uses: actions/checkout@v4
      #  with:
      #      fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"

  CheckoutTest2:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/applications/mnistcalculator/tensorflow
    timeout-minutes: 60
    steps:
      - name: Install Git (if not available)
        run: sudo apt-get install -y git

      - name: Manually Clone Repo
        run: |
          git clone https://github.com/${{ github.repository }}.git repo
          cd repo
          git checkout ${{ github.sha }}  # Checkout the exact commit
          ls

      - name: Verify Repo
        run: |
          ls

  CheckoutTest3:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/applications/mnistcalculator/tensorflow
    timeout-minutes: 60
    steps:
      - name: Manually Clone Repo
        run: |
          git clone --depth 1 https://${{github.REPOSITORY_OWNER}}:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }} repo
          cd repo
          ls

      - name: Verify Repo
        run: |
          ls
          cd repo
          ls


  CheckoutTest4:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/applications/mnistcalculator/tensorflow
    timeout-minutes: 60
    steps:
      - name: Manually Clone Repo
        run: |
          git clone --depth 1 https://${{github.REPOSITORY_OWNER}}:${{ secrets.ACCESS_TOKEN }}@github.com/DavidBlm/MNISTPipeline repo
          cd repo
          ls

      - name: Verify Repo
        run: |
          ls
          cd repo
          ls
