name: updatedImages
on:
  push:
  workflow_dispatch:
concurrency:
  group: "${{ github.ref }}"
  cancel-in-progress: true
jobs:
  MXNET170_v0-0-2:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/davidblm/mxnet170_update:0.0.2
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
  MXNET170_v0-0-1:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/mxnet170:v0.0.1
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
  TENSORFLOW:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/applications/mnistcalculator/tensorflow
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
  MXNET190_v0-0-2:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/davidblm/mxnet190_update:0.0.2
    timeout-minutes: 60
    steps:
      #- run: node -v
      #- run: nvm current
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
  TENSORFLOWONNX:
    runs-on: ubuntu-latest
    container: 
      image: registry.git.rwth-aachen.de/monticore/embeddedmontiarc/generators/emadl2cpp/dockerimages/tensorflow-onnx:latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            fetch-depth: 1
      - name: Echo
        run: echo "Image klappt"
